### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by G07cha** [avz/node-jl#1]
You create awesome module but here is only Russian localization what makes docs useless for non-russian developers.

**Comment by avz** [comment]
К сожалению, не настолько хорошо знаю английский, чтобы написать вменяемую документацию.

**Comment by G07cha** [comment]
Ok, let me translate for you and all community then.

**Comment by piranna** [comment]
Any update on this?

**Comment by G07cha** [comment]
Hi, @piranna, unfortunately, no, for some time I didn't have time to do a translation, but thanks for the reminder I think now I have time for this, expect English translation in few days.

**Comment by piranna** [comment]
I'm glad to have help you to remind this :-)

**Comment by piranna** [comment]
Some examples for using it programatically would be good too, it would allow to use the module as a simple and more portable option to SQLite (data would be directly legible by humans :-D),

**Comment by avz** [comment]
Now I had a lot of time to write a new version of the module that supports only SQL as a main functionality. Around the end of next week I plan to release an alpha version and, of course, the new version will be split into 2 parts: the API and CLI.

PS: I am glad to accept the PR with the translation into English of documentation for the current version, but I think we should wait a new version.

**Comment by piranna** [comment]
Having an API object and a CLI using it probably would be the best option to develop the module.

**Comment by G07cha** [comment]
Hi @avz, awesome, but I'm already started and almost half-way did it already 😆

**Comment by avz** [comment]
I think to be better if we have 2 separeted npm modules: one with API only and another with CLI.

**Comment by avz** [comment]
@G07cha challenge accepted!

**Comment by G07cha** [comment]
Done, @avz, @piranna please have a look on it and let me know what do you think!

**Comment by piranna** [comment]
LGTM

**Comment by piranna** [comment]
Now it's time to create a class with the core functionality :-)

**Comment by G07cha** [comment]
Let me know if there will be new content to translate!

**Comment by avz** [comment]
Finally I finished new version. It is completely rewritten and allows you to do a JOINs and data bindings: https://github.com/avz/node-jl-sql-api (`npm install jl-sql-api`). 

CLI-version is available here https://github.com/avz/jl-sql (`npm install -g jl-sql`).

**Comment by G07cha** [comment]
Awesome! Looks like CLI-version already has the complete english readme, right? I'll take a look at SQL API and submit a translation for it soon.

**Comment by avz** [comment]
> I'll take a look at SQL API and submit a translation for it soon.

It will be nice!

> Looks like CLI-version already has the complete english readme, right?

Yes, I think I'll just copy the section about SQL from the documentation for `jl-sql-api`

**Comment by piranna** [comment]
That's really cool, specially the `JOIN` addition! Good job! :-)

**Comment by piranna** [comment]
Is the SQL parser hardcoded, or are you using an external one? If not, maybe you could move it to an independent project in the next iteration ;-)

**Comment by avz** [comment]
> Is the SQL parser hardcoded, or are you using an external one? If not, maybe you could move it to an independent project in the next iteration ;-)

The parser generated from the grammar: https://github.com/avz/node-jl-sql-api/blob/master/src/sql/sql.jison If desired, it can be used separately, but I plan to extend the syntax incompatible with SQL features, so it is unlikely that the final version will be useful somewhere else.

**Comment by piranna** [comment]
I use to isolate and modularize things :-) Maybe the basic grammar could be usable by others... What additions are you planning to add?

**Comment by avz** [comment]
There are already incompatibilities, such as data bindings, `STRICT IN` (`IN` with strict type checking), field of any depth, not just `table.field`. I plan to add binding the field names to make it easier to automatically generate queries without having to do explicit escaping.
At the moment, that's all.

**Comment by avz** [comment]
Right now the implementation of AST is not completely separated from the main code. I will need a little work to separate fully

**Comment by avz** [comment]
I made a translation of README.md using the online translator and has made some corrections. I think even that is better than no translation - https://github.com/avz/node-jl-sql-api

**Comment by G07cha** [comment]
I was half-way done with translation couple days ago 😭 
Good that it's translated now anyway.

**Comment by avz** [comment]
I think a human translation much better than machine translation

**Comment by G07cha** [comment]
Engineers at Google has recently added neural networks to Google translate algorithms so it's pretty much like human 😆 
Okay, I'll try to minimize delay then.

**Comment by avz** [comment]
As far as I know, this engine is not yet listed for the Russian. In my opinion the translation from russian and to russian get better at Yandex.Translate

**Comment by piranna** [comment]
> As far as I know, this engine is not yet listed for the Russian. In my opinion the translation from russian and to russian get better at Yandex.Translate

Well, Yandex is the russian Google, so it makes sense ;-P
